apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: default
spec:
  secretName: demo-cert
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
      - DevOpsTeam
  commonName: demo.local
  dnsNames:
    - demo.local
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
