name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      RUNNER_TOOL_CACHE: $HOME/actions_cache
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r app/python/requirements.txt

    - name: Lint
      run: |
        pip install flake8
        flake8 app/

    - name: Run unit tests
      run: |
        pip install pytest
        pytest app/python/tests/unit

    - name: Build Docker image
      run: |
        docker build -t davismatrix/fta:latest .

    - name: Push to registry (if public or local)
      run: echo "push skipped"

    - name: Apply K8s manifests
      run: |
        kubectl apply -f manifests/ --validate=false

    - name: Wait for readiness
      run: |
        sleep 20
        kubectl wait --for=condition=ready pod -l app=demo --timeout=60s

    #- name: Run integration test
    #  run: curl http://demo.local/ready
